apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: helmupcheck
  name: helm-upcheck-monitor-private
  namespace: helmupcheck
spec:
  endpoints:
    - interval: 10m
      path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - helmupcheck
  selector:
    matchLabels:
      app.kubernetes.io/component: helmupcheck